name: Build

on:
  push:
    branches: [ poqdev ]
  pull_request:
    branches: [ poqdev ]

env:
  DOTNET_VERSION: 6.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build project
      run: dotnet build -c Release

    - name: Lint C# code
      run: dotnet format --verify-no-changes --exclude ACMESharpCore --verbosity detailed --no-restore