name: Publish

on:
  push:
    tags: [ v* ]

env:
  DOTNET_VERSION: 6.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setup_version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Version
      id: setup_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

    - name: Publish Functions
      run: dotnet publish -c Release -r win-x86 --self-contained false -o ./dist -p:Version=${{ steps.setup_version.outputs.version }} KeyVault.Acmebot

    - name: Zip Functions
      run: 7z a -mx=9 latest.zip ./dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          latest.zip

  deploy:
    environment: production
    needs: publish
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENTSECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'        

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist

    - name: Upload to Blob
      run: |
        az storage blob upload --auth-mode login -f latest.zip --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} -c keyvault-acmebot -n v4/latest.zip --overwrite
        az storage blob upload --auth-mode login -f latest.zip --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} -c keyvault-acmebot -n v4/${{ needs.publish.outputs.version }}.zip --overwrite
